import { BedrockOrchestrator } from '../backend/ai/bedrockOrchestrator';
import { IncidentRecord } from '../lib/types/database';

async function runTest() {
  console.log('=== SENTINEL Phase 4 (Amazon Bedrock) Verification ===\n');

  const dummyIncident: IncidentRecord = {
    PK: 'INCIDENT#inc-2026-0917-01',
    SK: 'METADATA',
    GSI1PK: 'STATUS#DETECTED',
    GSI1SK: `CREATED#${new Date().toISOString()}`,
    GSI2PK: 'SEV#SEV1',
    GSI2SK: `CREATED#${new Date().toISOString()}`,
    incidentId: 'inc-2026-0917-01',
    title: 'Payment Checkout Latency Spike (P99 > 3200ms)',
    severity: 'SEV1',
    service: 'payment-checkout-service',
    environment: 'production',
    commander: 'prana@sentinel.internal',
    status: 'DETECTED',
    summary: 'Post-deploy latency spike following release v2.14.0. Database connections saturated at 500/500.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  };

  const orchestrator = new BedrockOrchestrator();

  console.log('1. Testing retrieveRunbookEvidence...');
  const evidence = await orchestrator.retrieveRunbookEvidence(
    dummyIncident,
    'Active connections saturated at 500. ConnectionPoolTimeoutException.'
  );
  console.log(`-> Retrieved ${evidence.length} evidence chunks cleanly (no ValidationException).`);
  for (const chunk of evidence) {
    console.log(`   * [${chunk.chunkId}] ${chunk.documentTitle} (${chunk.sourceUri})`);
  }

  console.log('\n2. Testing live triageIncident via Bedrock Converse...');
  const triage = await orchestrator.triageIncident(dummyIncident, evidence);
  console.log('-> Bedrock Triage Result:');
  console.log('   * Root Cause Hypothesis:', triage.rootCauseHypothesis);
  console.log('   * Confidence Score:', triage.confidenceScore);
  console.log('   * Recommended Strategy:', triage.recommendedStrategy);
  console.log('   * Cited Evidence:', triage.citedEvidenceIds);
  console.log('   * Technical Summary:', triage.technicalSummary);

  console.log('\n3. Testing generateActionPlan...');
  const plan = await orchestrator.generateActionPlan(dummyIncident, triage);
  console.log(`-> Action Plan: ${plan.planSummary} (Risk: ${plan.overallRisk})`);
  for (const act of plan.actions) {
    console.log(`   - Action ${act.order} [${act.toolName}]: ${act.description} (Requires Approval: ${act.requiresApproval})`);
  }

  console.log('\n4. Testing live Next.js API triage endpoint...');
  try {
    const res = await fetch('http://localhost:3000/api/incidents/inc-2026-0917-01/triage', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        telemetrySnippet: 'Connections: 500/500. P99: 3450ms. HTTP 504 Rate: 14.2%.',
      }),
    });
    const status = res.status;
    const json = await res.json();
    console.log(`-> HTTP Status: ${status}`);
    console.log(`-> API Response Success: ${json.success}`);
    if (json.data?.triage) {
      console.log(`-> Live AI Hypothesis: "${json.data.triage.rootCauseHypothesis}"`);
      console.log(`-> AI Confidence: ${(json.data.triage.confidenceScore * 100).toFixed(1)}%`);
    }

    console.log('\n5. Testing live Next.js API action-plans endpoint...');
    const planRes = await fetch('http://localhost:3000/api/incidents/inc-2026-0917-01/action-plans', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    });
    const planJson = await planRes.json();
    console.log(`-> HTTP Status: ${planRes.status}`);
    console.log(`-> Plan Generated By Model: ${planJson.data?.generatedByModel}`);
    console.log(`-> Plan Summary: ${planJson.data?.summary}`);
    console.log(`-> Actions Count: ${planJson.data?.actions?.length}`);
  } catch (err: any) {
    console.warn('-> Note: Next.js dev server fetch test:', err.message);
  }

  console.log('\n=== Verification Complete ===');
}

runTest().catch((err) => {
  console.error('Test script failed:', err);
  process.exit(1);
});
